SELECT top 50000 POSTS.ID,
POSTS.PostTypeId,
POSTS.AcceptedAnswerId,
POSTS.ParentId,
POSTS.CreationDate,
POSTS.DeletionDate,
POSTS.Score,
POSTS.ViewCount,
POSTS.Body,
POSTS.OwnerUserId,
USERS.DisplayName,
POSTS.LastEditorUserId,
POSTS.LastEditorDisplayName,
POSTS.LastEditDate,
POSTS.LastActivityDate,
POSTS.Title,
POSTS.Tags,
POSTS.AnswerCount,
POSTS.CommentCount,
POSTS.FavoriteCount,
POSTS.ClosedDate,
POSTS.CommunityOwnedDate
FROM posts INNER JOIN users ON posts.OWNERUSERID = users.ID
ORDER BY posts.ViewCount DESC
